#pragma compile(out, "hm-holv.exe")
#pragma compile(icon, "hm-holv.ico")
#pragma compile(ExecLevel, asInvoker)
#pragma compile(UPX, true)
#pragma compile(Compression, 9)
#pragma compile(Comments, "")
#pragma compile(FileVersion, 20141115)
#pragma compile(OriginalFilename, "hm-holv.exe")
#pragma compile(ProductName, "HM:HoLV CWcheat Cheatfile Editor")
#pragma compile(ProductVersion, 2014.11.15.1b-wine)
#include "variables.au3"
#include "functions.au3"
Opt("GUICloseOnESC", 0)
Opt("GUIOnEventMode", 1)
Opt("TrayIconHide", 1)
Opt("TrayOnEventMode", 1)
_LoadCfg()
ProgressOn("HM:HoLV CWcheat Cheatfile Editor", "Loading...", "Please wait while main interface is being loaded.")
$Form = GUICreate("HM:HoLV CWcheat Cheatfile Editor", 458, 352, -1, -1)
GUISetIcon(@ScriptDir&"\hm-holv.ico")
GUISetOnEvent($GUI_EVENT_CLOSE, "Close", $Form)
GUICtrlCreatePic(@ScriptDir&"\hm-holv-box.jpg", 0, 0, 209, 352)
$TreeView = GUICtrlCreateTreeView(209, 0, 249, 351-((24*3)+(4*5)), BitOR($GUI_SS_DEFAULT_TREEVIEW,$TVS_CHECKBOXES,$WS_VSCROLL))
$TreeView1 = GUICtrlCreateTreeViewItem("General", $TreeView)
GUICtrlSetOnEvent(-1, "_CheckAllTreeView1")
_StaticCheatsTreeItem()
$TreeView2 = GUICtrlCreateTreeViewItem("Date and time", $TreeView)
GUICtrlSetOnEvent(-1, "_CheckTreeView2")
$TreeView3 = GUICtrlCreateTreeViewItem("Affection", $TreeView)
GUICtrlSetOnEvent(-1, "_CheckAllTreeView3")
GUICtrlCreateTreeViewItem("Dog", $TreeView3)
GUICtrlCreateTreeViewItem("Horse", $TreeView3)
GUICtrlCreateTreeViewItem("Villagers", $TreeView3)
GUICtrlSetOnEvent(-1, "_CheckTreeView3")
$TreeView4 = GUICtrlCreateTreeViewItem("Backpack", $TreeView)
GUICtrlCreateTreeViewItem("Tools", $TreeView4)
GUICtrlSetOnEvent(-1, "_CheckTreeView4_1")
GUICtrlCreateTreeViewItem("Items", $TreeView4)
GUICtrlSetOnEvent(-1, "_CheckTreeView4_2")
$TreeView5 = GUICtrlCreateTreeViewItem("Storage", $TreeView)
GUICtrlCreateTreeViewItem("Toolbox", $TreeView5)
GUICtrlSetOnEvent(-1, "_CheckTreeView5_1")
GUICtrlCreateTreeViewItem("Fridge", $TreeView5)
GUICtrlSetOnEvent(-1, "_CheckTreeView5_2")
Local $a = 211
Local $b = 261
Local $c = 245
Local $d = 29
GUICtrlCreateButton("Add cheat(s) to cheatfile file", $a, $b+(($d+1)*0), $c, $d)
GUICtrlSetOnEvent(-1, "_AddCheats")
GUICtrlSetFont(-1, 8, 800, 0, "MS Sans Serif")
GUICtrlCreateButton("Preview cheats", $a, $b+(($d+1)*1), ($c/2), $d)
GUICtrlSetOnEvent(-1, "_PreviewCheatCodes")
GUICtrlCreateButton("Minimize to Tray", $a+($c/2)+1, $b+(($d+1)*1), ($c/2), $d)
GUICtrlSetOnEvent(-1, "_MinToTray")
GUICtrlCreateButton("Help", $a, $b+(($d+1)*2), $c/3, $d)
GUICtrlSetOnEvent(-1, "_Help")
GUICtrlCreateButton("About", $a+(($c/3)*1)+1, $b+(($d+1)*2), $c/3, $d)
GUICtrlSetOnEvent(-1, "_About")
GUICtrlCreateButton("Reset", $a+(($c/3)*2)+1, $b+(($d+1)*2), $c/3, $d)
GUICtrlSetOnEvent(-1, "_Reset")
ProgressSet(30)
Form0()
ProgressSet(40)
Form1()
ProgressSet(50)
Form2()
ProgressSet(60)
Form3()
ProgressSet(70)
Form4()
ProgressSet(80)
Form5()
ProgressSet(90)
ProgressSet(100, " ", "Complete")
Sleep(500)
ProgressOff()
GUISetState(@SW_SHOW, $Form)
While 1
WEnd
